name: Create Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Package JSON Info
        uses: myrotvorets/info-from-package-json-action@1.1.0
        id: pkgjson

      - name: Generate docs
        run: |
          node sdkdo docs
          zip -r docs.zip docs-${{ steps.pkgjson.outputs.packageVersion }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apidocs
          path: docs.zip
